map $http_accept_language $header_lang {
	default en-US;
	~*^en-US en-US;
	~*^en en-US;
	~*^ar ar;
	~*^cs cs;
	~*^da da;
	~*^de de;
	~*^es es;
	~*^fa fa;
	~*^fr fr;
	~*^ko ko;
	~*^it it;
	~*^he he;
	~*^ka ka;
	~*^hu hu;
	~*^mk mk;
	~*^nl nl;
	~*^ja ja;
	~*^nb nb;
	~*^pl pl;
	~*^pt pt;
	~*^ro ro;
	~*^ru ru;
	~*^sl sl;
	~*^fi fi;
	~*^sv sv;
	~*^th th;
	~*^tr tr;
	~*^uk uk;
	~*^vi vi;
	~*^zh zh;
	~*^hi hi;
	~*^ne ne;
	~*^lt lt;
	~*^hr hr;
}

map $cookie_lang $lang {
	default $header_lang;
	~*^en-US en-US;
	~*^en en-US;
	~*^ar ar;
	~*^cs cs;
	~*^da da;
	~*^de de;
	~*^es es;
	~*^fa fa;
	~*^fr fr;
	~*^ko ko;
	~*^it it;
	~*^he he;
	~*^ka ka;
	~*^hu hu;
	~*^mk mk;
	~*^nl nl;
	~*^ja ja;
	~*^nb nb;
	~*^pl pl;
	~*^pt pt;
	~*^ro ro;
	~*^ru ru;
	~*^sl sl;
	~*^fi fi;
	~*^sv sv;
	~*^th th;
	~*^tr tr;
	~*^uk uk;
	~*^vi vi;
	~*^zh zh;
	~*^hi hi;
	~*^ne ne;
	~*^lt lt;
	~*^hr hr;
}

server {
	listen 0.0.0.0:8080;
	access_log /var/log/nginx/access_mempool.log;
	error_log /var/log/nginx/error_mempool.log;

	root /var/www/mempool/browser;
	index index.html;

	add_header Cache-Control "public, no-transform";
	add_header Vary Accept-Language;
	add_header Vary Cookie;

__MEMPOOL_EXACT_BASE_LOCATION__

	location __MEMPOOL_BASE_PATH__/ {
__MEMPOOL_PREFIX_REWRITE__
		try_files /$lang$uri /$lang$uri/ $uri $uri/ /en-US$uri @index-redirect;
		expires 10m;
	}

	location __MEMPOOL_BASE_PATH__/resources {
__MEMPOOL_PREFIX_REWRITE__
		try_files $uri @index-redirect;
		expires 1h;
	}

	location __MEMPOOL_BASE_PATH__/resources/config. {
__MEMPOOL_PREFIX_REWRITE__
		try_files $uri =404;
		expires 5m;
	}

	location __MEMPOOL_BASE_PATH__/resources/customize. {
__MEMPOOL_PREFIX_REWRITE__
		try_files $uri =404;
		expires 5m;
	}

	location @index-redirect {
		rewrite (.*) __MEMPOOL_BASE_PATH__/$lang/index.html;
	}

	location ~ ^__MEMPOOL_BASE_PATH__/(ar|bg|bs|cs|da|de|et|el|es|eo|eu|fa|fr|gl|ko|hr|id|it|he|ka|lv|lt|hu|mk|ms|nl|ja|nb|nn|pl|pt|pt-BR|ro|ru|sk|sl|sr|sh|fi|sv|th|tr|uk|vi|zh|hi)/ {
__MEMPOOL_PREFIX_REWRITE__
		try_files $uri $uri/ /$1/index.html =404;
	}

	location = __MEMPOOL_BASE_PATH__/api {
__MEMPOOL_PREFIX_REWRITE__
		try_files $uri $uri/ /en-US/index.html =404;
	}

	location = __MEMPOOL_BASE_PATH__/api/ {
__MEMPOOL_PREFIX_REWRITE__
		try_files $uri $uri/ /en-US/index.html =404;
	}

	location __MEMPOOL_BASE_PATH__/api/v1/ws {
__MEMPOOL_PREFIX_REWRITE__
		proxy_pass http://127.0.0.1:8999/;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "Upgrade";
	}

	location __MEMPOOL_BASE_PATH__/api/v1/services {
		default_type application/json;
		return 200 '{}';
	}

	location __MEMPOOL_BASE_PATH__/api/v1 {
__MEMPOOL_PREFIX_REWRITE__
		proxy_pass http://127.0.0.1:8999/api/v1;
	}

	location __MEMPOOL_BASE_PATH__/api/ {
__MEMPOOL_PREFIX_REWRITE__
		proxy_pass http://127.0.0.1:8999/api/v1/;
	}

	location __MEMPOOL_BASE_PATH__/ws {
__MEMPOOL_PREFIX_REWRITE__
		proxy_pass http://127.0.0.1:8999/;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "Upgrade";
	}
}
